export const FORMATS: Record<string, string> = {
  ST: 'Standard',
  PI: 'Pioneer',
  MO: 'Modern',
  LE: 'Legacy',
  VI: 'Vintage',
  PAU: 'Pauper',
  cEDH: 'cEDH',
  EDH: 'Duel Commander',
  PREM: 'Premodern',
  EXP: 'Explorer',
  HI: 'Historic',
  ALCH: 'Alchemy',
  PEA: 'Peasant',
  BL: 'Block',
  EX: 'Extended',
  HIGH: 'Highlander',
  CHL: 'Canadian Highlander',
}

export const META_EDH: Record<string, string> = {
  'Last 7 Days': '328',
  'Last 2 Weeks': '115',
  'Last 2 Months': '121',
  'MTGO Last 2 Months': '306',
  'Paper Last 2 Months': '308',
  'Last Major Events (3 Months)': '130',
  'Last 6 Months': '209',
  'All 2026 Decks': '343',
  'All 2025 Decks': '310',
  'All 2024 Decks': '283',
  'All 2023 Decks': '252',
  'Major Events': '196',
  'All Commander decks': '56',
}
